from pathlib import Path
import tempfile
import unittest
from unittest.mock import patch

from backend.final_generation import build_plan
from backend import ml_model
from config_generation.schemas import ConfigPlan, Manifest, ParameterCatalog, PlanItem
from config_generation.onboarding import onboard
from config_generation.renderers import render_key_value
from config_generation.policy import validate_plan


class OnboardingTests(unittest.TestCase):
    def test_key_value_renderer_comments_metadata_header(self):
        catalog = ParameterCatalog.model_validate({
            "app_id": "sample",
            "parameters": [{
                "id": "sample.background",
                "name": "background",
                "type": "color",
            }],
        })
        output = render_key_value([(catalog.parameters[0], "#112233")])
        self.assertTrue(output.startswith("# Generated by Ricifier\n"))

    def test_onboarding_skips_wrapped_numeric_defaults(self):
        with tempfile.TemporaryDirectory() as directory:
            tmp_path = Path(directory)
            docs = tmp_path / "docs.txt"
            docs.write_text(
                "margin\n¶\nmargin\n0\n.0 0.0\n"
                "The margin has two numeric values.\n",
                encoding="utf-8",
            )
            paths = onboard("sample", "Sample", [str(docs)], tmp_path / "app")
            catalog = __import__("json").loads(
                paths["catalog"].read_text(encoding="utf-8")
            )
            self.assertEqual(catalog["parameters"], [])

    def test_sphinx_keymap_examples_are_not_settings(self):
        catalog = __import__("backend.config_generation.onboarding", fromlist=["extract_parameters"]).extract_parameters(
            "kitty",
            "Move tab backward\n¶\nmap\nctrl+shift+,\nmove_tab_backward\n"
            "background\n¶\nbackground\n#112233\nA background color.\n",
            "source",
        )
        self.assertEqual([parameter.name for parameter in catalog.parameters], ["background"])

    def test_theme_enforces_mood_and_readable_foreground(self):
        palette = ["#202020", "#303030", "#ff0000"]
        reply = (
            '{"background": {"color": "#ff0000", "reason": "bright"}, '
            '"foreground": {"color": "#303030", "reason": "muted"}, '
            '"accent": {"color": "#ff0000", "reason": "strong"}}'
        )
        with patch.object(ml_model, "_load_image", return_value=object()), \
                patch.object(ml_model, "_generate", return_value=reply):
            theme = ml_model.design_theme(
                b"wallpaper",
                {"mode": "dark"},
                palette,
            )

        self.assertEqual(theme["background"]["color"], "#202020")
        self.assertEqual(theme["foreground"]["color"], "#f2f2f2")
        self.assertGreaterEqual(
            ml_model._contrast(
                theme["background"]["color"],
                theme["foreground"]["color"],
            ),
            4.5,
        )

    def test_onboard_local_key_value_docs(self):
        with tempfile.TemporaryDirectory() as directory:
            tmp_path = Path(directory)
            docs = tmp_path / "sample.conf"
            docs.write_text(
                "background #112233\n"
                "foreground #ddeeff\n"
                "font_size 12\n"
                "shell /bin/sh\n",
                encoding="utf-8",
            )
            output = tmp_path / "app"
            paths = onboard("sample", "Sample", [str(docs)], output)

            self.assertEqual(set(paths), {"manifest", "catalog", "template"})
            template = paths["template"].read_text(encoding="utf-8")
            self.assertIn("background {{sample.background}}", template)
            self.assertIn("foreground {{sample.foreground}}", template)
            self.assertNotIn("shell", template)

    def test_onboard_sphinx_html_extracts_defaults(self):
        with tempfile.TemporaryDirectory() as directory:
            tmp_path = Path(directory)
            docs = tmp_path / "docs.html"
            docs.write_text(
                "<html><body><dl><dt>Color scheme</dt><dt>¶</dt>"
                "<dt>foreground</dt><span>¶</span><span>foreground</span>"
                "<span>#ddeeff</span><span>background</span><span>#112233</span>"
                "</body></html>",
                encoding="utf-8",
            )
            paths = onboard("sample", "Sample", [str(docs)], tmp_path / "app")
            names = {
                item["name"]
                for item in __import__("json").loads(
                    paths["catalog"].read_text(encoding="utf-8")
                )["parameters"]
            }
            self.assertEqual(names, {"foreground", "background"})

    def test_constraints_are_extracted_from_documentation(self):
        with tempfile.TemporaryDirectory() as directory:
            tmp_path = Path(directory)
            docs = tmp_path / "docs.txt"
            docs.write_text(
                "tab_bar_style\n¶\n"
                "tab_bar_style\nfade\n"
                "The tab bar style can be one of:\n"
                "fade\nFade style.\n"
                "powerline\nPowerline style.\n"
                "hidden\nHidden style.\n"
                "background_opacity\n¶\n"
                "background_opacity\n1.0\n"
                "The opacity is a number between zero and one.\n",
                encoding="utf-8",
            )
            paths = onboard("sample", "Sample", [str(docs)], tmp_path / "app")
            parameters = {
                item["name"]: item
                for item in __import__("json").loads(
                    paths["catalog"].read_text(encoding="utf-8")
                )["parameters"]
            }
            tab = parameters["tab_bar_style"]
            self.assertEqual(tab["type"], "enum")
            self.assertEqual(
                tab["constraints"]["enum_values"],
                ["fade", "powerline", "hidden"],
            )
            opacity = parameters["background_opacity"]
            self.assertEqual(opacity["constraints"]["min"], 0)
            self.assertEqual(opacity["constraints"]["max"], 1)

    def test_final_plan_maps_design_values_to_catalog(self):
        catalog = ParameterCatalog.model_validate({
            "app_id": "sample",
            "parameters": [
                {
                    "id": "sample.background",
                    "name": "background",
                    "type": "color",
                    "capability": "colors",
                    "constraints": {"pattern": r"^#[0-9a-fA-F]{6}$"},
                    "risk": {"level": "safe", "classified_by": "rule"},
                    "verification": {"status": "reviewed", "extracted_by": "deterministic"},
                },
                {
                    "id": "sample.font_size",
                    "name": "font_size",
                    "type": "float",
                    "capability": "typography",
                    "constraints": {"min": 9, "max": 16},
                    "verification": {"status": "reviewed", "extracted_by": "deterministic"},
                },
            ],
        })
        plan = build_plan(
            "sample",
            catalog,
            {"background": {"color": "#112233"}},
            {"typography": {"size": 12}},
        )
        self.assertEqual(
            [(item.parameter_id, item.value) for item in plan.items],
            [("sample.background", "#112233"), ("sample.font_size", 12)],
        )

    def test_presentation_settings_receive_safe_capabilities(self):
        with tempfile.TemporaryDirectory() as directory:
            tmp_path = Path(directory)
            docs = tmp_path / "kitty.conf"
            docs.write_text(
                "background #112233\n"
                "font_size 11.0\n"
                "window_padding_width 4\n"
                "background_opacity 1.0\n",
                encoding="utf-8",
            )
            paths = onboard("kitty", "Kitty", [str(docs)], tmp_path / "kitty")
            parameters = {
                item["name"]: item
                for item in __import__("json").loads(
                    paths["catalog"].read_text(encoding="utf-8")
                )["parameters"]
            }
            self.assertEqual(parameters["font_size"]["capability"], "typography")
            self.assertEqual(parameters["window_padding_width"]["capability"], "geometry")
            self.assertEqual(parameters["background_opacity"]["capability"], "visual_effects")

    def test_policy_result_can_be_rendered(self):
        catalog = ParameterCatalog.model_validate({
            "app_id": "sample",
            "parameters": [
                {
                    "id": "sample.background",
                    "name": "background",
                    "type": "color",
                    "capability": "colors",
                    "constraints": {"pattern": r"^#[0-9a-fA-F]{6}$"},
                    "risk": {"level": "safe", "classified_by": "rule"},
                    "verification": {"status": "reviewed", "extracted_by": "deterministic"},
                },
            ],
        })
        parameter = catalog.parameters[0]
        output = render_key_value([(parameter, "#112233")])
        self.assertIn("background #112233", output)

    def test_policy_result_summary_uses_parameter_id(self):
        catalog = ParameterCatalog.model_validate({
            "app_id": "sample",
            "parameters": [
                {
                    "id": "sample.background",
                    "name": "background",
                    "type": "color",
                    "capability": "colors",
                    "constraints": {"pattern": r"^#[0-9a-fA-F]{6}$"},
                    "risk": {"level": "safe", "classified_by": "rule"},
                    "verification": {"status": "reviewed", "extracted_by": "deterministic"},
                },
            ],
        })
        manifest = Manifest.model_validate({
            "id": "sample",
            "display_name": "Sample",
            "tier": "generic",
            "config": {"format": "key-value"},
        })
        result = validate_plan(
            ConfigPlan(
                app_id="sample",
                items=[PlanItem(parameter_id="sample.background", value="#112233")],
            ),
            catalog,
            manifest,
        )
        self.assertEqual(
            [item.parameter_id for _, _, item in result.accepted],
            ["sample.background"],
        )
