"""Deterministic renderers for validated application configuration plans."""

from __future__ import annotations

from collections.abc import Iterable

from .schemas import ParameterRecord, SyntaxStyle


class RendererError(ValueError):
    """Raised when a catalog cannot be rendered by the selected renderer."""


def render_key_value(
    items: Iterable[tuple[ParameterRecord, object]],
    *,
    comment: str = "#",
) -> str:
    """Render ``name value`` settings from policy-approved parameter values."""
    lines = ["Generated by Ricifier", ""]
    for parameter, value in items:
        if parameter.syntax.style is not SyntaxStyle.KEY_VALUE:
            raise RendererError(
                f"{parameter.id} uses unsupported syntax "
                f"{parameter.syntax.style.value!r} for key-value rendering"
            )
        description = " ".join(parameter.description.split())
        if description:
            lines.append(f"{comment} {description}")
        lines.append(f"{parameter.name} {value}")
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def render_template(
    parameters: Iterable[ParameterRecord],
    *,
    comment: str = "#",
) -> str:
    """Render a reusable key-value template with catalog-backed placeholders."""
    lines = ["Generated by Ricifier", ""]
    for parameter in parameters:
        if parameter.syntax.style is not SyntaxStyle.KEY_VALUE:
            raise RendererError(
                f"{parameter.id} uses unsupported syntax "
                f"{parameter.syntax.style.value!r} for key-value templates"
            )
        description = " ".join(parameter.description.split())
        if description:
            lines.append(f"{comment} {description}")
        lines.append(f"{parameter.name} {{{{{parameter.id}}}}}")
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"
